Add global radiation flux, temperature and referentiegewasverdamping
nens/raster-feeder pull request #7
Opened 2018-03-27 13:20 UTC by caspervdw

Ook een hoop tests voor Harmonie en Steps. Ik heb Harmonie op een gezamelijke FTPServer gebaseerd. De common FTPServer wordt getest met een open FTP server van tele2.

2018-03-30 14:15 UTC, arjanverkerk requested changes
Fijn dat je al die code test die ik niet heb getest... Wil je ook nog master erin mergen zodat hij up to date is?

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/config.py
> +        'group': 'harmonie-zlto',
ZLTO is denk ik de naam van de tuinbouworganisatie. Ik stel '-evap' als postfix voor.

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/rotate.py
> +from ..common import rotate, touch_lizard, FTPServer
de download() wordt hiermee overbodig, dus die kan weg.

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/rotate.py
> +    """Slope of the vapor pressure curve in kPa / deg C, KNMI formula
Graasg een bronvermelding van de KNMI formule toevoegen. Als ik het goed begrijp is dat de bron die bij makkink() wordt genoemd? Dan moet die denk ik hier staan.

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/rotate.py
> +    return ET_ref / (rho * lambd) * 3600 * 24  # [m / d]
Moet mm / dag zijn van Lex.

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/rotate.py
> +    gamma = 0.066   # pscychrometric constant [kPa / degC]
Een 'c' teveel, maar je mag wikipedia de schuld geven. Wiki heb ik inmiddels aangepast :-)

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/harmonie/rotate.py
> +    T = temperature - 273.15
Persoonlijk zou ik die kelvins niet zover doorlaten dringen in de berekening. Als de formule is niet geldig voor temperaturen in de buurt van het absolute nulpunt. Wat mij betreft converteren we al bij het aanroepen van makkink() naar celsius.

2018-03-30 14:15 UTC, arjanverkerk commented on raster_feeder/tests/test_harmonie.py
> +from raster_feeder.harmonie.rotate import extract_regions, rotate_harmonie, \
Persoonlijk vind ik dit niet zo mooi. Dan heb ik liever een extra 'from' regel. Maar ik laat het aan jou over.

2018-04-03 08:02 UTC, caspervdw commented
Done @arjanverkerk

2018-04-03 08:25 UTC, arjanverkerk approved these changes

2018-04-03 08:25 UTC, merged